#!/usr/bin/env python
# -*- coding: CP936 -*-
#
# generated by wxGlade 0.6.8 (standalone edition) on Tue Dec 17 10:34:28 2013
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade
import mongo_bll
# begin wxGlade: extracode
# end wxGlade


class DB_view(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: DB_view.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.db_list = wx.ListBox(self, wx.ID_ANY, choices=[])
        self.sizer_13_staticbox = wx.StaticBox(self, wx.ID_ANY, "Database")
        self.collect_list = wx.ListBox(self, wx.ID_ANY, choices=[])
        self.sizer_14_staticbox = wx.StaticBox(self, wx.ID_ANY, "Collection")
        self.key_list = wx.ListBox(self, wx.ID_ANY, choices=[])
        self.sizer_15_staticbox = wx.StaticBox(self, wx.ID_ANY, "keys")
        self.value_list = wx.ListBox(self, wx.ID_ANY, choices=[])
        self.sizer_16_staticbox = wx.StaticBox(self, wx.ID_ANY, "Values")
        self.sizer_11_staticbox = wx.StaticBox(self, wx.ID_ANY, "DB_view")
        
        db_name = mongo_bll.getDB_names()
        self.db_list.AppendItems(db_name)
        
        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_LISTBOX_DCLICK, self.DCLICK_DB, self.db_list)
        self.Bind(wx.EVT_LISTBOX_DCLICK, self.DCLICK_COLLECT, self.collect_list)
        self.Bind(wx.EVT_LISTBOX_DCLICK, self.DCLICK_KEYS, self.key_list)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: DB_view.__set_properties
        self.SetTitle("DB_view")
        icon = wx.EmptyIcon()
        icon.CopyFromBitmap(wx.Bitmap("E:\\Test\\Icons\\cube\\103.ico", wx.BITMAP_TYPE_ANY))
        self.SetIcon(icon)
        self.SetSize((700, 400))
        self.SetBackgroundColour(wx.Colour(240, 240, 240))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: DB_view.__do_layout
        sizer_10 = wx.BoxSizer(wx.VERTICAL)
        self.sizer_11_staticbox.Lower()
        sizer_11 = wx.StaticBoxSizer(self.sizer_11_staticbox, wx.HORIZONTAL)
        sizer_12 = wx.BoxSizer(wx.HORIZONTAL)
        self.sizer_16_staticbox.Lower()
        sizer_16 = wx.StaticBoxSizer(self.sizer_16_staticbox, wx.VERTICAL)
        self.sizer_15_staticbox.Lower()
        sizer_15 = wx.StaticBoxSizer(self.sizer_15_staticbox, wx.VERTICAL)
        self.sizer_14_staticbox.Lower()
        sizer_14 = wx.StaticBoxSizer(self.sizer_14_staticbox, wx.VERTICAL)
        self.sizer_13_staticbox.Lower()
        sizer_13 = wx.StaticBoxSizer(self.sizer_13_staticbox, wx.VERTICAL)
        sizer_13.Add(self.db_list, 1, wx.EXPAND, 0)
        sizer_12.Add(sizer_13, 1, wx.EXPAND, 0)
        sizer_14.Add(self.collect_list, 1, wx.EXPAND, 0)
        sizer_12.Add(sizer_14, 1, wx.EXPAND, 0)
        sizer_15.Add(self.key_list, 1, wx.EXPAND, 0)
        sizer_12.Add(sizer_15, 1, wx.EXPAND, 0)
        sizer_16.Add(self.value_list, 1, wx.EXPAND, 0)
        sizer_12.Add(sizer_16, 1, wx.EXPAND, 0)
        sizer_11.Add(sizer_12, 1, wx.EXPAND, 0)
        sizer_10.Add(sizer_11, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_10)
        self.Layout()
        # end wxGlade

    def DCLICK_DB(self, event):  # wxGlade: DB_view.<event_handler>
        print "Event handler 'DCLICK_DB' not implemented!"
        self.db = event.GetString()
        collect_name = mongo_bll.getCollect_names(self.db)
        try:
            self.collect_list.Clear()
            for i in collect_name:
                self.collect_list.Append(i)
        except:
            event.Skip()

    def DCLICK_COLLECT(self, event):  # wxGlade: DB_view.<event_handler>
        print "Event handler 'DCLICK_COLLECT' not implemented!"
        self.collect = event.GetString()
        key_name = mongo_bll.getAttriName(self.db, self.collect)
        try:
            self.key_list.Clear()
            for i in key_name:
                self.key_list.Append(i)
        except:
            event.Skip()

    def DCLICK_KEYS(self, event):  # wxGlade: DB_view.<event_handler>
        print "Event handler 'DCLICK_KEYS' not implemented!"
        self.key = event.GetString()
        value = mongo_bll.getAttriValue(self.db,self.collect,self.key)
        try:
            self.value_list.Clear()
            for i in value:
                print i.values()
                self.value_list.Append(str(i.values()[0]))
        except:    
            event.Skip()

# end of class DB_view
if __name__ == "__main__":
    #gettext.install("app") # replace with the appropriate catalog name

    app = wx.PySimpleApp(0)
    #wx.InitAllImageHandlers()
    frame_1 = DB_view(None)
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
    
