#!/usr/bin/env python
# -*- coding: CP936 -*-
#
# generated by wxGlade 0.6.8 (standalone edition) on Sat Dec 28 12:47:03 2013
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade
import global_ID as ID

class module_name(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: module_name.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.text_ctrl_1 = wx.TextCtrl(self, wx.ID_ANY, "")
        self.sure_btn = wx.Button(self, wx.ID_ANY, "sure")
        self.cancel_btn = wx.Button(self, wx.ID_ANY, "cancel")
        self.sizer_2_staticbox = wx.StaticBox(self, wx.ID_ANY, "insert module name")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.sure_btn_event, self.sure_btn)
        self.Bind(wx.EVT_BUTTON, self.cancel_btn_event, self.cancel_btn)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: module_name.__set_properties
        self.SetTitle("set_module_name")
        
        self.SetBackgroundColour(wx.Colour(240, 240, 240))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: module_name.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        self.sizer_2_staticbox.Lower()
        sizer_2 = wx.StaticBoxSizer(self.sizer_2_staticbox, wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3.Add(self.text_ctrl_1, 0, wx.EXPAND, 0)
        sizer_4.Add((20, 20), 3, wx.EXPAND, 0)
        sizer_4.Add(self.sure_btn, 0, 0, 0)
        sizer_4.Add(self.cancel_btn, 0, 0, 0)
        sizer_3.Add(sizer_4, 1, wx.EXPAND, 0)
        sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def sure_btn_event(self, event):  # wxGlade: module_name.<event_handler>
        if self.text_ctrl_1.GetValue() == "":
            id_num = ID.ID_LIST[0]
            ID.ID_MODULE_NAME = ID.ID_NAME[id_num]
        else:
            ID.ID_MODULE_NAME = self.text_ctrl_1.GetValue()          
        self.Close()
        #event.Skip()

    def cancel_btn_event(self, event):  # wxGlade: module_name.<event_handler>
        try:
            id_num = ID.ID_LIST[0]
            ID.ID_MODULE_NAME = ID.ID_NAME[id_num]
            self.Close()            
        except:
            print "module_name error"
        
    
    
        #event.Skip()

# end of class module_name
if __name__ == "__main__":
    gettext.install("app") # replace with the appropriate catalog name

    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = module_name(None, wx.ID_ANY, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()